version: "3"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "posts_db"
    ports:
      - "5432:5432"

  sonarqube:
    image: sonarqube:lts
    ports:
      - "9000:9000"
    networks:
      - sonarnet

networks:
  sonarnet:
    driver: bridge
